### ISSUE TITLE
Incorrect link in repository description

### ISSUE THREAD

**Issue by iamc** [scw-ss/2018-06-27-cfmehu-python-ecology-lesson#4]
Link in the repository description points to the original datacarpentry repository github pages instead to this one.

**Comment by daviddesancho** [comment]
Where exactly do you mean? In the README file? There is even the name of a maintainer who is not us. But in a way maybe that should be kept that way, not as if we were the lesson maintainers. Maybe we should just replace the README file and explain that this is just a clone for teaching purposes of the original lessons from Data Carpentry?

**Comment by iamc** [comment]
In the code tab, at the top, it reads:

>  Data Carpentry Python lessons on ecology. http://datacarpentry.github.io/python… 

Click the  ``Edit`` button and set the correct ULR for this repo, https://scw-ss.github.io/2018-06-27-cfmehu-python-ecology-lesson/

I'd also change the description to something like:

> Data Carpentry python-ecology lesson freezed for 2018-06-27-cfmehu workshop

**Comment by daviddesancho** [comment]
Sorted!
